world:
  build: ../world/
  container_name: world
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20000
    - LISTENER_PORT=9999
    - area_PORT=10001
    - registration_PORT=10002
  ports:
    - 10000:20000
  links:
    - rabbitmq
    - mongo

area:
  build: ../area/
  container_name: area
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20001
    - world_PORT=10001
    - registration_PORT=10002
  ports:
    - 10001:20001
  links:
    - rabbitmq
    - mongo

registration:
  build: ../registration/
  container_name: registration
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20002
    - world_PORT=10000
    - area_PORT=10001
  ports:
    - 10002:20002
  links:
    - rabbitmq
    - mongo

rabbitmq:
  image: rabbitmq:3.6
  ports:
    - 5672:5672

mongo:
  image: mongo:3.2
  ports:
    - 27017:27017
