coordinator:
  build: ../coordinator/
  container_name: coordinator
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20000
#    - PROXY_HOST=set this to the docker-machine ip address or local machine address on linux
    # - frontend_PORT=10000
    # - service1_PORT=10001
    # - service2_PORT=10002
  ports:
    - 10000:20000
  links:
    rabbitmq
network-listener:
  build: ../network-listener/
  container_name: network-listener
  environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=20001
#    - PROXY_HOST=set this to the docker-machine ip address or local machine address on linux
    # - frontend_PORT=10000
    # - service1_PORT=10001
    # - service2_PORT=10002
  ports:
    - 10001:20001
